### ISSUE TITLE
generate.py fails: "Model filename ./YourMusicLibraryNPWeights25 could not be found!"

### ISSUE THREAD

**Issue by drscotthawley** [MattVitelli/GRUV#16]
To fix this: The code generate.py, as it stands in the repo, includes the line
cur_iter = 25
Just changing the 25 to a 50 fixed the issue.   

Not sure if this is worth a pull/fork; still adding it here for future users.

**Comment by karolmajek** [comment]
Agree with PS: ("model._predict")

Traceback (most recent call last):
  File "generate.py", line 59, in <module>
    sequence_length=max_seq_len, data_variance=X_var, data_mean=X_mean)
  File "GRUV/gen_utils/sequence_generator.py", line 13, in generate_from_seed
    seedSeqNew = model._predict(seedSeq) #Step 1. Generate X_n + 1
AttributeError: 'Sequential' object has no attribute '_predict'

**Comment by subzerofun** [comment]
@drscotthawley Hey thanks for the fixes, but i still get the error that the file couldn't be found. Do you know what else i could try?
