### ISSUE TITLE
Error during training first epoch

### ISSUE THREAD

**Issue by HandsomeDevilv112** [MattVitelli/GRUV#18]
Apologies, but I'm a little out of my element and I haven't found an answer I find as actionable during my efforts to find an answer. I have the "yourmusiclibrary" files in the proper place after conversion, but I get an error immediately when training.

al@al-System-Product-Name:~/GRUV$ python train.py
Using Theano backend.
Loading training data
Finished loading training data
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:1021: UserWarning: TimeDistributedDense is deprecated, please use TimeDistributed(Dense(...)) instead.
  warnings.warn('TimeDistributedDense is deprecated, '
Starting training!
Iteration: 0
Epoch 1/25
Traceback (most recent call last):
  File "train.py", line 48, in <module>
    history = model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=epochs_per_iter, verbose=1, validation_split=0.0)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 429, in fit
    sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1108, in fit
    callback_metrics=callback_metrics)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 846, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 39, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 195, in on_epoch_end
    self.progbar.update(self.seen, self.log_values, force=True)
AttributeError: 'ProgbarLogger' object has no attribute 'log_values'

**Comment by robeau** [comment]
I'm getting exactly the same error. I tried setting verbose=0, which allows train.py to finish without an error, but it skips straight from iteration 0 to iteration 25, and I get a different error when running generate.py

**Comment by piteight** [comment]
Hi there, I had the same issue, but in my log there was memory error also. The solution was to decrease number of music samples in datasets. When I changed it from 20 samples to 11, error vanished.

**Comment by freemso** [comment]
I got this issue too. And I somehow solve this by manually split validation set and pass a `validation_data` rather than using `validation_split` argument.

**Comment by vladbph** [comment]
When using fit() Keras should throw an exception when using validation_split and training set is ended up to be 0... Example: your last batch in epoch contains 1 sample and validation_split = 0.3 => training size = 0...
When training set size is 0 you will see this exception...
If you look at callbacks.py in keras, class ProgbarLogger, log_values member is created ONLY when batch starts... So if you don't have data in the batch it gets to on_epoch_end with log_values undefined...

**Comment by wangzhenhui1992** [comment]
Check if your training data is empty.

**Comment by VBota1** [comment]
> When using fit() Keras should throw an exception when using validation_split and training set is ended up to be 0... Example: your last batch in epoch contains 1 sample and validation_split = 0.3 => training size = 0...
> When training set size is 0 you will see this exception...
> If you look at callbacks.py in keras, class ProgbarLogger, log_values member is created ONLY when batch starts... So if you don't have data in the batch it gets to on_epoch_end with log_values undefined...

I got this error when the batch size parameter exceeded the number of samples :rofl:
