### ISSUE TITLE
Error in generate.py: AttributeError: 'Sequential' object has no attribute '_predict'

### ISSUE THREAD

**Issue by laggingreflex** [MattVitelli/GRUV#23]
Getting this error in `generate.py` 

    $ python generate.py
    Using Theano backend.
    Loading training data
    Finished loading training data
    Starting generation!
    Traceback (most recent call last):
      File "generate.py", line 59, in <module>
        sequence_length=max_seq_len, data_variance=X_var, data_mean=X_mean)
      File "/mnt/c/forks/GRUV/gen_utils/sequence_generator.py", line 13, in generate_from_seed
        seedSeqNew = model._predict(seedSeq) #Step 1. Generate X_n + 1
    AttributeError: 'Sequential' object has no attribute '_predict'

I'm just using the `test.mp3` already provided with the library.

**Comment by akgun1** [comment]
See #19
