### ISSUE TITLE
local variable 'epoch_logs' referenced before assignment

### ISSUE THREAD

**Issue by mordigann228** [MattVitelli/GRUV#29]
While using train.py I get

> Starting training!
Iteration: 0
Epoch 0
Traceback (most recent call last):
  File "train.py", line 48, in <module>
    history = model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=epochs_per_iter, verbose=1, validation_split=0.0)
  File "build\bdist.win-amd64\egg\keras\models.py", line 204, in fit
UnboundLocalError: local variable 'epoch_logs' referenced before assignment

anyone encountered with this? and how can this be solved?
Using keras 0.1.0 on windows 10 if that makes difference

**Comment by joeyearsley** [comment]
When I've had that it is from the data not being loaded properly, check your inputs.
