### ISSUE TITLE
I can't run convert_directory.py successfully 

### ISSUE THREAD

**Issue by Hiurge** [MattVitelli/GRUV#32]
python /home/l/GRUV-master/convert_directory.py
Traceback (most recent call last):
  File "/home/l/GRUV-master/convert_directory.py", line 13, in <module>
    new_directory = convert_folder_to_wav(input_directory, freq)
  File "/home/l/GRUV-master/data_utils/parse_files.py", line 56, in convert_folder_to_wav
    for file in os.listdir(directory):
OSError: [Errno 2] No such file or directory: './datasets/YourMusicLibrary/'

Any ideas what i can do? Program looks cool.

**Comment by ianni67** [comment]
Do you actually have a datasets/YouMusicLibrary directory in your GRUV directory? 
Does such directory actually contain the "Test.mp3" file?
If the directory and the file are there, then it looks like you've got some misconfiguration in your shell. Try setting the whole absolute path of the dataset directory (instead of ./dataset...) in the config/nn_config.py file (raw 12). If this error disappears, then you've definitely got something wrong in the shell configuration.
