### ISSUE TITLE
python convert_directory.py

### ISSUE THREAD

**Issue by odomojuli** [MattVitelli/GRUV#33]
Can't convert test.mp3

> Traceback (most recent call last):
>   File "convert_directory.py", line 1, in <module>
>     from data_utils.parse_files import *
>   File "/Users/odomojuli/GRUV/data_utils/parse_files.py", line 124
>     print 'Processing: ', (file_idx+1),'/',num_files
>

**Comment by bgroenks96** [comment]
That doesn't look like the entirety of the error output. Could you post the whole thing?

**Comment by BenAsaf** [comment]
I am guessing this is the same error I had. I used 'python3' instead of 'python'.
If that's the case you can either: Use 'python' to run or attempt to convert the project to support python3

**Comment by vgcapizzi** [comment]
Im experiencing the same issue. Im using anaconda with python3.

**Comment by bgroenks96** [comment]
Again, I can't really help without seeing more output. If that really is the entirety of the error message, add `-d` and maybe `-v` to make python tell you more.

**Comment by vgcapizzi** [comment]
I got the program convert_directory.py to run in a python2 environment that I made in anaconda3. The code exclusively works with python2. The issue im having now is running the python2 environment to run the code and run the tensorflow environment to supply the backend. Does anyone know if I can run both environments at the same time to run train.py?

**Comment by CygnusiaX1** [comment]
The error is likely this, as I am currently getting it:
`Traceback (most recent call last):
  File "convert_directory.py", line 1, in <module>
    from data_utils.parse_files import *
  File "C:\GRUV\data_utils\parse_files.py", line 124
    print 'Processing: ', (file_idx+1),'/',num_files
                       ^
SyntaxError: invalid syntax`
