### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by vgcapizzi** [MattVitelli/GRUV#34]
I cant successfully run convert_directory without getting an assertion error. 

Flushing to disk...
Traceback (most recent call last):
  File "C:\Users\vgcap_000\Desktop\toKeep\College Stuff\Notes by Class\COM 321\musicMakingAI\GRUV-master\convert_directory.py", line 15, in <module>
    convert_wav_files_to_nptensor(new_directory, block_size, max_seq_len, output_filename)
  File "C:\Users\vgcap_000\Desktop\toKeep\College Stuff\Notes by Class\COM 321\musicMakingAI\GRUV-master\data_utils\parse_files.py", line 156, in convert_wav_files_to_nptensor
    np.save(out_file+'_mean', mean_x)
  File "C:\Python27\lib\site-packages\numpy\lib\npyio.py", line 511, in save
    pickle_kwargs=pickle_kwargs)
  File "C:\Python27\lib\site-packages\numpy\lib\format.py", line 562, in write_array
    version)
  File "C:\Python27\lib\site-packages\numpy\lib\format.py", line 308, in _write_array_header
    header = asbytes(_filter_header(header))
  File "C:\Python27\lib\site-packages\numpy\lib\format.py", line 467, in _filter_header
    return tokenize.untokenize(tokens)
  File "C:\Python27\lib\tokenize.py", line 262, in untokenize
    return ut.untokenize(iterable)
  File "C:\Python27\lib\tokenize.py", line 198, in untokenize
    self.add_whitespace(start)
  File "C:\Python27\lib\tokenize.py", line 187, in add_whitespace
    assert row <= self.prev_row
AssertionError

I have installed the necessary dependencies. This whole thing just fails whenever it has to output the training files. Please let me know if someone has come across a fix! Thanks

**Comment by mryanfei** [comment]
I got the same error on centos7, python 2.7
[root@centos7 GRUV]# python2 convert_directory.py
LAME 3.100 64bits (http://lame.sf.net)
Autoconverting from stereo to mono. Setting encoding to mono mode.
Using polyphase lowpass filter, transition band: 16538 Hz - 17071 Hz
Encoding ./datasets/YourMusicLibrary/Test.mp3
      to ./datasets/YourMusicLibrary/tmp/Test.mp3
Encoding as 44.1 kHz single-ch MPEG-1 Layer III (11x)  64 kbps qval=3
    Frame          |  CPU time/estim | REAL time/estim | play/CPU |    ETA 
  7488/7488  (100%)|    0:09/    0:09|    0:09/    0:09|   20.376x|    0:00 
-------------------------------------------------------------------------------
   kbps       mono %     long switch short %                                   
   64.0      100.0        99.3   0.4   0.3                                     
Writing LAME Tag...done
ReplayGain: -0.5dB
input:  ./datasets/YourMusicLibrary/tmp/Test.mp3
	(44.1 kHz, 1 channel, MPEG-1 Layer III)
output: ./datasets/YourMusicLibrary/wave/Test.wav  (16 bit, Microsoft WAVE)
skipping initial 1105 samples (encoder+decoder delay)
skipping final 1088 samples (encoder padding-decoder delay)
Frame#  7488/7488    64 kbps                 
Processing:  1 / 1
Filename:  ./datasets/YourMusicLibrary/wave/Test.wav
783
40
Saved example  1  /  19
Saved example  2  /  19
Saved example  3  /  19
Saved example  4  /  19
Saved example  5  /  19
Saved example  6  /  19
Saved example  7  /  19
Saved example  8  /  19
Saved example  9  /  19
Saved example  10  /  19
Saved example  11  /  19
Saved example  12  /  19
Saved example  13  /  19
Saved example  14  /  19
Saved example  15  /  19
Saved example  16  /  19
Saved example  17  /  19
Saved example  18  /  19
Saved example  19  /  19
Flushing to disk...
Traceback (most recent call last):
  File "convert_directory.py", line 15, in <module>
    convert_wav_files_to_nptensor(new_directory, block_size, max_seq_len, output_filename)
  File "/root/GRUV/data_utils/parse_files.py", line 156, in convert_wav_files_to_nptensor
    np.save(out_file+'_mean', mean_x)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 511, in save
    pickle_kwargs=pickle_kwargs)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/format.py", line 562, in write_array
    version)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/format.py", line 308, in _write_array_header
    header = asbytes(_filter_header(header))
  File "/usr/lib64/python2.7/site-packages/numpy/lib/format.py", line 467, in _filter_header
    return tokenize.untokenize(tokens)
  File "/usr/lib64/python2.7/tokenize.py", line 262, in untokenize
    return ut.untokenize(iterable)
  File "/usr/lib64/python2.7/tokenize.py", line 198, in untokenize
    self.add_whitespace(start)
  File "/usr/lib64/python2.7/tokenize.py", line 187, in add_whitespace
    assert row <= self.prev_row
AssertionError

**Comment by mryanfei** [comment]
solve this problem by downgrade numpy version from 1.14.0 to 1.13.3
pip install numpy==1.13.3

you can see this issue
https://github.com/numpy/numpy/issues/10348

**Comment by vgcapizzi** [comment]
Amazing! Changing it to numpy 1.13.3 totally worked. Thank you!
