### ISSUE TITLE
slice indeces must be integers

### ISSUE THREAD

**Issue by dandavies80** [MattVitelli/GRUV#39]
I got a type error when running the convert_directory.py file.  Any ideas?

Traceback (most recent call last):
  File "convert_directory.py", line 15, in <module>
    convert_wav_files_to_nptensor(new_directory, block_size, max_seq_len, output_filename)
  File "/Users/dan/Documents/python/GRUV-master/data_utils/parse_files.py", line 126, in convert_wav_files_to_nptensor
    X, Y = load_training_example(file, block_size, useTimeDomain=useTimeDomain)
  File "/Users/dan/Documents/python/GRUV-master/data_utils/parse_files.py", line 172, in load_training_example
    x_t = convert_np_audio_to_sample_blocks(data, block_size)
  File "/Users/dan/Documents/python/GRUV-master/data_utils/parse_files.py", line 81, in convert_np_audio_to_sample_blocks
    block = song_np[num_samples_so_far:num_samples_so_far+block_size]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by varesh007** [comment]
Same issue here, did you manage to fix it?

**Comment by varesh007** [comment]
Managed to fix it. 
In convert_directory.py, cast the block size as int to avoid any other problems
