### ISSUE TITLE
train.py with TensorFlow backend

### ISSUE THREAD

**Issue by MartinThoma** [MattVitelli/GRUV#6]
When I execute `train.py` with the TensorFlow backend I get

```text
Using TensorFlow backend.
Loading training data
Finished loading training data
Start creating the network
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 12
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:888] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:88] Found device 0 with properties: 
name: GeForce GTX TITAN Black
major: 3 minor: 5 memoryClockRate (GHz) 0.98
pciBusID 0000:01:00.0
Total memory: 6.00GiB
Free memory: 5.79GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:112] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:122] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:643] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN Black, pci bus id: 0000:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:47] Setting region size to 5906808832
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 12
Traceback (most recent call last):
  File "train.py", line 28, in <module>
    model = network_utils.create_lstm_network(num_frequency_dimensions=freq_space_dims, num_hidden_dimensions=hidden_dims)
  File "/home/moose/GitHub/GRUV/nn_utils/network_utils.py", line 13, in create_lstm_network
    model.compile(loss='mean_squared_error', optimizer='rmsprop')
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 406, in compile
  File "build/bdist.linux-x86_64/egg/keras/layers/containers.py", line 128, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 1048, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 159, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/recurrent.py", line 127, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 159, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 1054, in get_output
  File "build/bdist.linux-x86_64/egg/keras/backend/tensorflow_backend.py", line 388, in rnn
  File "/home/moose/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 238, in unpack
    raise ValueError("Cannot infer num from shape %s" % shape)
ValueError: Cannot infer num from shape TensorShape([Dimension(None), Dimension(None), Dimension(22050)])
```

**Comment by anayebi** [comment]
Hi Martin,

Thanks for the message. At the moment, we don't have support for TensorFlow
as a backend, since the Keras version we use is from August (5 months ago).
As Keras is changing pretty rapidly, it's hard to keep up with major API
changes, though an upgrade of GRUV is on the backlog. In the meantime, if
you check out an earlier version of Keras, GRUV ought to work fine.

**Comment by MartinThoma** [comment]
Could you please add which exact version (git hash) you use?

**Comment by anayebi** [comment]
Not sure exactly about the hash, but Keras version 0.1.0 will work.
